17_220704_DJANGO05/sus-3-project-canary/survey/urls.py
from django.urls import path

from survey import views


# urlpatterns = [
#     path("submit-simple/", views.create_survey_simple),
#     path("result-simple/", views.read_all_survey_simple),
#     path("result-simple/<int:survey_id>/", views.read_survey_simple),
#     path("submit-choice/", views.create_survey_choice),
#     path("result-choice/", views.read_all_survey_choice),
#     path("result-choice/<int:survey_id>/", views.read_survey_choice),
# ]

app_name = "survey"

urlpatterns = [
    path("submit-simple/", views.create_survey_simple, name = "submit-simple"),
    path("result-simple/", views.read_all_survey_simple, name = "result-simple"),
    path("result-simple/<int:survey_id>/", views.read_survey_simple, name = "result-simple_survey_id"),
    path("submit-choice/", views.create_survey_choice, name = "submit-choice"),
    path("result-choice/", views.read_all_survey_choice, name = "result-choice"),
    path("result-choice/<int:survey_id>/", views.read_survey_choice, name = "result-choice_survey_id"),
]

17_220704_DJANGO05/sus-3-project-canary/survey/views.py
from django.shortcuts import render, redirect

from survey.models import SurveySimple, SurveyChoices


def create_survey_simple(request):
    if request.method == "POST":
        new_survey = SurveySimple()
        new_survey.age = request.POST.get("age")
        new_survey.gender = request.POST.get("gender")
        new_survey.address = request.POST.get("address")
        new_survey.suggestions = request.POST.get("suggestions")
        new_survey.save()

        # return redirect("/survey/submit-simple/")
        return redirect("survey:submit-simple")
    elif request.method == "GET":
        return render(request, "survey/create-simple.html")


def read_all_survey_simple(request):
    survey_list = SurveySimple.objects.all()
    context = {
        "survey_list": survey_list,
        "survey_count": len(survey_list),
    }
    return render(request, "survey/results-simple.html", context)


def read_survey_simple(request, survey_id):
    survey = SurveySimple.objects.get(id=survey_id)
    context = {
        "survey": survey
    }
    return render(request, "survey/results-simple-one.html", context)


def create_survey_choice(request):
    if request.method == "POST":
        new_survey = SurveyChoices()
        new_survey.age = request.POST.get("age")
        new_survey.gender = request.POST.get("gender")
        new_survey.address = request.POST.get("address")
        new_survey.suggestions = request.POST.get("suggestions")
        new_survey.save()

        # return redirect("/survey/submit-choice/")
        return redirect("survey:submit-choice")
    elif request.method == "GET":
        return render(request, "survey/create-choice.html")


def read_all_survey_choice(request):
    survey_list = SurveyChoices.objects.all()
    context = {
        "survey_list": survey_list,
        "survey_count": len(survey_list),
    }
    return render(request, "survey/results-choice.html", context)


def read_survey_choice(request, survey_id):
    survey = SurveyChoices.objects.get(id=survey_id)
    context = {
        "survey": survey
    }
    return render(request, "survey/results-choice-one.html", context)

17_220704_DJANGO05/sus-3-project-canary/survey/templates/survey/create-choice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- <form action="/survey/submit-choice/" method="post"> -->
    <form action="{% url 'survey:submit-choice' %}" method="post">
        {% csrf_token %}
        <div>
            <label>나이: <input id="input-age" type="number" name="age" /></label>
        </div>
        <div>
            성별 <br>
            <label>남성:<input id="input-gender" type="radio" name="gender" value="M"/></label> <br>
            <label>여성:<input id="input-gender" type="radio" name="gender" value="F"/></label> <br>
            <label>응답거부:<input id="input-gender" type="radio" name="gender" value="O"/></label>
        </div>
        <div>
            <label>주소: <input id="input-address" type="text" name="address"/></label>
        </div>
        <div>
            <label for="textarea-suggestion">건의사항:<br></label>
            <textarea 
                name="suggestions" 
                id="textarea-suggestion"
                placeholder="건의 사항을 작성하세요"
            ></textarea>
        </div>
        <input type="submit" value="제출" />
    </form>
</body>
</html>

17_220704_DJANGO05/sus-3-project-canary/survey/templates/survey/create-simple.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- <form action="/survey/submit-simple/" method="post"> -->
    <form action="{% url 'survey:submit-simple' %}" method="post">
        {% csrf_token %}
        <div>
            <label>나이: <input id="input-age" type="number" name="age" /></label>
        </div>
        <div>
            <label>성별: <input id="input-gender" type="text" name="gender"/></label>
        </div>
        <div>
            <label>주소: <input id="input-address" type="text" name="address"/></label>
        </div>
        <div>
            <label for="textarea-suggestion">건의사항:<br></label>
            <textarea 
                name="suggestions" 
                id="textarea-suggestion"
                placeholder="건의 사항을 작성하세요"
            ></textarea>
        </div>
        <input type="submit" value="제출" />
    </form>
</body>
</html>

17_220704_DJANGO05/sus-3-project-canary/survey/templates/survey/results-choice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h2>Total: {{ survey_count }}</h2>
    </div>
    {% for survey in survey_list %}
    <ul>
        <li>
            <!-- <a href="/survey/result-choice/{{ survey.id }}/"> -->
            <a href="{% url 'survey:result-choice_survey_id' survey.id %}">
                {{ survey.age }}, {{ survey.address }}
            </a>
        </li>
    </ul>
    {% endfor %}
</body>
</html>

17_220704_DJANGO05/sus-3-project-canary/survey/templates/survey/results-simple.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Total: {{ survey_count }}</h2>
    {% for survey in survey_list %}
    <ul>
        <li>
            <!-- <a href="/survey/result-simple/{{ survey.id }}/"> -->
            <a href="{% url 'survey:result-simple_survey_id' survey.id %}">
                {{ survey.age }}, {{ survey.address }}
            </a>
        </li>
    </ul>
    {% endfor %}
</body>
</html>